#ifndef GOLANGPLS_GLOBAL_H
#define GOLANGPLS_GLOBAL_H

#if defined(GOLANGPLS_LIBRARY)
#  define GOLANGPLSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define GOLANGPLSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif// GOLANGPLS_GLOBAL_H